version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "Gradle"

  - package-ecosystem: "docker"
    directory: "/app"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "Docker"

  - package-ecosystem: "docker"
    directory: "/sporingslogg-cleanup"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "Docker"

  - package-ecosystem: "docker"
    directory: "/hent-utenlandsadresser"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Europe/Oslo"
    commit-message:
      prefix: "Docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "GitHub Actions"
