apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: "utenlandsadresser"
  namespace: "utenlandsadresser"
  labels:
    "team": "utenlandsadresser"
  annotations:
    "start.nais.io/created-by": "Odd Gunnar Fatland"
    "start.nais.io/creationTimestamp": "2023-12-01T09:37:06.559796741"
spec:
  groups:
    - name: "utenlandsadresser-alerts"
      rules:
        - alert: "utenlandsadresser er nede"
          description: "App {{ $labels.app }} er nede i namespace {{ $labels.namespace }}"
          expr: >
            kube_deployment_status_replicas_unavailable{deployment="utenlandsadresser"} > 0
          for: "2m"
          action: >
            kubectl describe pod {{ $labels.pod }} -n {{ $labels.namespace }}` for events, og `kubectl logs {{ $labels.pod }} -n {{ $labels.namespace }}` for logger
          labels:
            "severity": "warning"
          annotations:
            "consequence": "utenlandsadresser gjør ikke det den skal"
            "action": "Fiks den!"
            "sla": "Innen 3 timer i kontortid"
            "documentation": "https://github.com/navikt/utenlandsadresser/somedoc"
        - alert: "Feil i loggene"
          expr: >
            sum by(level) (increase(logback_events_total{app="utenlandsadresser", level="error"}[3m])) > 0
          for: "3m"
          action: >
            Sjekk loggene til app {{ $labels.app }} i namespace {{ $labels.namespace }} for å se hvorfor det er feil
          labels:
            severity: "critical"
            send_resolved: false
          annotations:
            "consequence": "utenlandsadresser gjør ikke det den skal"
            "action": "Fiks den!"
            "sla": "Innen 3 timer i kontortid"
            "documentation": "https://github.com/navikt/utenlandsadresser/somedoc"
