apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: "utenlandsadresser"
  namespace: "utenlandsadresser"
  labels:
    "team": "utenlandsadresser"
  annotations:
    "start.nais.io/created-by": "Odd Gunnar Fatland"
    "start.nais.io/creationTimestamp": "2023-12-01T09:37:06.559796741"
spec:
  groups:
    - name: "utenlandsadresser-alerts"
      rules:
        - alert: "utenlandsadresser er nede"
          expr: >
            kube_deployment_status_replicas_unavailable{deployment="utenlandsadresser"} > 0
          for: "2m"
          labels:
            "namespace": "utenlandsadresser"
            "severity": "warning"
          annotations:
            "consequence": "utenlandsadresser gjør ikke det den skal"
            "action": "Fiks den!"
            "sla": "Innen 3 timer i kontortid"
            "documentation": "https://github.com/navikt/utenlandsadresser/somedoc"
        - alert: "Feil i loggene"
          expr: >
            sum by(level) (increase(logback_events_total{app="utenlandsadresser", level="error"}[3m])) > 0
          for: "3m"
          labels:
            namespace: "utenlandsadresser"
            severity: "critical"
            send_resolved: false
          annotations:
            "consequence": "utenlandsadresser gjør ikke det den skal"
            "action": "Sjekk loggene og fiks eventuelle feil."
            "sla": "Innen 3 timer i kontortid"
            "documentation": "https://github.com/navikt/utenlandsadresser/somedoc"
