apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: "utenlandsadresser"
  namespace: "utenlandsadresser"
  labels:
    "team": "utenlandsadresser"
  annotations:
    "start.nais.io/created-by": "Odd Gunnar Fatland"
    "start.nais.io/creationTimestamp": "2023-12-01T09:37:06.559796741"
spec:
  groups:
    - name: "utenlandsadresser-alerts"
      rules:
        - alert: "problemer med deployment av utenlandsadresser"
          expr: >
            kube_deployment_status_replicas_unavailable{deployment="utenlandsadresser"} > 0
          for: "5m"
          labels:
            "namespace": "utenlandsadresser"
            "severity": "warning"
          annotations:
            "consequence": "utenlandsadresser har problemer med å deploye"
            "action": "Fiks den!"
        - alert: "Feil i loggene"
          expr: >
            sum(increase(logback_events_total{app="utenlandsadresser", level="error"}[3m])) > 0
          labels:
            namespace: "utenlandsadresser"
            severity: "critical"
            send_resolved: false
          annotations:
            "consequence": "utenlandsadresser gjør ikke det den skal"
            "action": "Sjekk loggene og fiks eventuelle feil."
        - alert: "Feil i sporingslogg-cleanup"
          expr: >
            sum(increase(logback_events_total{app="sporingslogg-cleanup", level="error"}[3m])) > 0
          labels:
            namespace: "utenlandsadresser"
            severity: "critical"
            send_resolved: false
          annotations:
            "consequence": "sporingslogg-cleanup gjør ikke det den skal"
            "action": "Sjekk loggene og fiks eventuelle feil."
