ingresses:
  - "https://utenlandsadresser.intern.dev.nav.no"
  - "https://utenlandsadresser.ekstern.dev.nav.no"

env:
  APP_ENV: "dev-gcp"

accessPolicy:
  outbound:
    external:
      - host: "regoppslag.dev-fss-pub.nais.io"

maskinporten:
  consumers:
    - "889640782" # NAV
    - "974761076" # Skatteetaten

kafka:
  pool:
    - "nav-dev"
