ingresses:
  - "https://utenlandsadresser.intern.dev.nav.no"
env:
  KTOR_ENV: "dev-gcp"

accessPolicy:
  outbound:
    external:
      - host: "regoppslag.dev-fss-pub.nais.io"

maskinporten:
  consumers:
    - "889640782" # NAV
    - "974761076" # Skatteetaten
