ingresses:
  - "https://utenlandsadresser.intern.dev.nav.no"
env:
  KTOR_ENV: "dev-gcp"

accessPolicy:
  outbound:
    rules:
      - application: "regoppslag"
        namespace: "teamdokumenthandtering"
        cluster: "dev-gcp"
