apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "utenlandsadresser"
  namespace: "utenlandsadresser"
  labels:
    "team": "utenlandsadresser"
  annotations:
    "start.nais.io/created-by": "Odd Gunnar Fatland"
    "start.nais.io/creationTimestamp": "2023-12-01T09:37:06.559796741"
spec:
  image: {{ image }}
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "postadresse.read"
          enabled: true
          product: "utenlandsadresser"
          consumers:
            {{#each maskinporten.consumers}}
            - orgno: "{{this}}"
            {{/each}}
      consumes:
        - name: "nav:utenlandsadresser:postadresse.read"
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        {{#each accessPolicy.outbound.external}}
        - host: {{this.host}}
        {{/each}}
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: abonnement
  env:
    {{#each env}}
    - name: {{@key}}
      value: {{this}}
    {{/each}}
  envFrom:
    - secret: "dev-api-credentials"
    - secret: "behandlingsnummer"
  liveness:
    path: "/isalive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isready"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
    {{#each ingresses}}
    - {{this}}
    {{/each}}