apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "utenlandsadresser"
  namespace: "utenlandsadresser"
  labels:
    "team": "utenlandsadresser"
  annotations:
    "start.nais.io/created-by": "Odd Gunnar Fatland"
    "start.nais.io/creationTimestamp": "2023-12-01T09:37:06.559796741"
spec:
  observability:
    logging:
      destinations:
        - id: "loki"
  ingresses:
    {{#each ingresses}}
    - {{this}}
    {{/each}}
  kafka:
    {{#each kafka.pool}}
    pool: "{{this}}"
    {{/each}}
  image: {{ image }}
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "postadresse.read"
          enabled: true
          product: "utenlandsadresser"
          consumers:
            {{#each maskinporten.consumers}}
            - orgno: "{{this}}"
            {{/each}}
      consumes:
        - name: "nav:utenlandsadresser:postadresse.read"
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        {{#each accessPolicy.outbound.external}}
        - host: {{this.host}}
        {{/each}}
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: utenlandsadresser
  env:
    {{#each env}}
    - name: {{@key}}
      value: {{this}}
    {{/each}}
  envFrom:
    - secret: "behandlingsnummer"
  liveness:
    failureThreshold: 3
    initialDelay: 40
    path: "/internal/isalive"
    periodSeconds: 10
    timeout: 1
  readiness:
    failureThreshold: 3
    initialDelay: 40
    path: "/internal/isready"
    periodSeconds: 10
    timeout: 1
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/internal/metrics"
  resources:
    limits:
      cpu: "200m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "1024Mi"
