ingresses:
  - "https://utenlandsadresser.intern.nav.no"
env:
  KTOR_ENV: "prod-gcp"

accessPolicy:
  outbound:
    external:
      - host: "regoppslag.prod-fss-pub.nais.io"
maskinporten:
  consumers:
    - "974761076" # Skatteetaten
