apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: utenlandsadresser
  name: sporingslogg-cleanup
  namespace: utenlandsadresser
spec:
#   schedule: "0 0 1 * *" # Run at 00:00 on the first day of every month
  restartPolicy: "OnFailure"
  image: {{image}} # Placeholder variable to be replaced by the CI/CD pipeline
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
  accessPolicy:
    outbound:
      rules:
        - application: utenlandsadresser
  env:
    {{#each env}}
    - name: {{@key}}
      value: {{this}}
    {{/each}}
