services:
  utenlandsadresser:
    build: .
    depends_on:
      db:
        condition: service_healthy

    ports:
      - 8080:8080

  db:
    image: postgres:18-alpine
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_USER: utenlandsadresser
      POSTGRES_PASSWORD: utenlandsadresser
      POSTGRES_DB: utenlandsadresser
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
