ingresses:
  - "https://utenlandsadresser.intern.dev.nav.no"
  - "https://utenlandsadresser.ekstern.dev.nav.no"

env:
  APP_ENV: "dev-gcp"
  JDK_JAVA_OPTIONS: "-XX:+UseParallelGC -XX:ActiveProcessorCount=4"

accessPolicy:
  outbound:
    external:
      - host: "regoppslag.dev-fss-pub.nais.io"
  inbound:
    rules:
      - application: sporingslogg-cleanup
      - application: hent-utenlandsadresser

maskinporten:
  consumers:
    - "889640782" # NAV
    - "974761076" # Skatteetaten

kafka:
  pool:
    - "nav-dev"

gcp:
  sqlInstances:
    tier: db-f1-micro

replicas:
  min: 1
  max: 2
  scalingStrategy:
    cpu:
      thresholdPercentage: 100

resources:
  requests:
    cpu: 5m
    memory: 440Mi
