ingresses:
  - "https://utenlandsadresser.nav.no"

env:
  APP_ENV: "prod-gcp"
  JDK_JAVA_OPTIONS: "-XX:+UseParallelGC -XX:ActiveProcessorCount=4"

accessPolicy:
  outbound:
    external:
      - host: "regoppslag.prod-fss-pub.nais.io"
  inbound:
    rules:
      - application: sporingslogg-cleanup

maskinporten:
  consumers:
    - "974761076" # Skatteetaten

kafka:
  pool:
    - "nav-prod"

gcp:
  sqlInstances:
    tier: db-custom-1-3840

resources:
  requests:
    cpu: 6m
    memory: 320Mi
