name: "Deploy Alerts"
on:
  workflow_dispatch: {}
  push:
    branches:
      - "main"
    paths:
      - '.nais/alerts.yaml'
      - '.github/workflows/alerts.yaml'
jobs:
  deployAlertsToDev:
    name: "Deploy alerts to dev"
    runs-on: "ubuntu-24.04"
    environment: "dev-gcp"
    permissions:
        id-token: "write"
    steps:
      - uses: "actions/checkout@v5"
      - name: "Deploy alerts to DEV"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          "CLUSTER": "dev-gcp"
          "RESOURCE": "app/.nais/alerts.yaml"
          "VARS": "app/.nais/vars/dev.yaml"

  deployAlertsToProd:
    name: "Deploy alerts to prod"
    environment: "prod-gcp"
    runs-on: "ubuntu-24.04"
    permissions:
        id-token: "write"
    steps:
      - uses: "actions/checkout@v5"
      - name: "Deploy alerts to PROD"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          "CLUSTER": "prod-gcp"
          "RESOURCE": "app/.nais/alerts.yaml"
          "VARS": "app/.nais/vars/prod.yaml"