name: "CI/CD Pipeline for app"
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
      - ".nais/alerts.yaml"
      - ".github/workflows/alerts.yaml"
      - "sporingslogg-cleanup/**"
      - "hent-utenlandsadresser/**"

permissions:
  id-token: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yaml
    secrets: inherit
    with:
      service_name: "app"
      docker_context: "./app"
      dockerfile: "./app/Dockerfile"
      resource_file: ".nais/nais.yaml"