name: "Reusable Build and Deploy"
on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      docker_context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      resource_file:
        required: true
        type: string

jobs:
  build:
    name: "Build and test"
    runs-on: "ubuntu-20.04"
    permissions:
      id-token: "write"
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: "actions/checkout@v4"
      - uses: "gradle/actions/wrapper-validation@v3"
      - uses: "actions/setup-java@v4"
        with:
          java-version: "21"
          distribution: "temurin"
      - uses: "gradle/actions/setup-gradle@v3"
      - name: "Compile and run tests"
        run: "./gradlew ${{ inputs.service_name }}:test ${{ inputs.service_name }}:installDist"
      - uses: "nais/docker-build-push@v0"
        if: github.ref == 'refs/heads/main'
        id: docker-build-push
        with:
          docker_context: ${{ inputs.docker_context }}
          dockerfile: ${{ inputs.dockerfile }}
          image_suffix: ${{ inputs.service_name }}
          team: "utenlandsadresser"
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    name: "Deploy to DEV"
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-20.04"
    permissions:
      id-token: "write"
    environment: "dev-gcp"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to DEV"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          CLUSTER: "dev-gcp"
          RESOURCE: ${{ inputs.resource_file }}
          VAR: "image=${{ needs.build.outputs.image }}"
          VARS: ".nais/vars/dev.yaml"

  deploy-prod:
    name: "Deploy to PROD"
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-20.04"
    permissions:
      id-token: "write"
    environment: "prod-gcp"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to PROD"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          CLUSTER: "prod-gcp"
          RESOURCE: ${{ inputs.resource_file }}
          VAR: "image=${{ needs.build.outputs.image }}"
          VARS: ".nais/vars/prod.yaml"