name: "CI/CD Pipeline for app"
on:
  push:
    paths-ignore:
      - "**.md"
      - ".nais/alerts.yaml"
      - ".github/workflows/alerts.yaml"
      - "sporingslogg-cleanup/**"
      - "hent-utenlandsadresser/**"

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yaml@main
    with:
      service_name: "app"
      docker_context: "./app"
      dockerfile: "./app/Dockerfile"
      resource_file: ".nais/nais.yaml"