name: "CI/CD Pipeline for utenlandsadresser"
on:
  push:
    paths-ignore:
      - "**.md"
      - "**/**.md"
      - ".nais/alerts.yaml"
      - ".github/workflows/alerts.yaml"

jobs:
  build:
    name: "Build and test"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "gradle/wrapper-validation-action@v2"
      - uses: "actions/cache@v4"
        with:
          path: "~/.gradle/caches"
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}"
          restore-keys: "${{ runner.os }}-gradle-"
      - uses: "actions/setup-java@v4"
        with:
          java-version: "17"
          distribution: "temurin"
      - name: "Compile and run tests"
        run: "./gradlew build"

  dockerBuildPush:
    name: "Docker build and push"
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-20.04"
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    permissions:
      id-token: "write"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "nais/docker-build-push@v0"
        id: "docker-build-push"
        with:
          team: "utenlandsadresser"
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    name: "Deploy to DEV"
    needs: dockerBuildPush
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-20.04"
    environment: dev-gcp
    permissions:
      id-token: "write"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to DEV"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          CLUSTER: "dev-gcp"
          RESOURCE: ".nais/nais.yaml"
          VAR: "image=${{ needs.dockerBuildPush.outputs.image }}"
          VARS: ".nais/dev.yaml"

  deploy-prod:
    name: "Deploy to PROD"
    needs: dockerBuildPush
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-20.04"
    environment: prod-gcp
    permissions:
      id-token: "write"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to PROD"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          CLUSTER: "prod-gcp"
          RESOURCE: ".nais/nais.yaml"
          VAR: "image=${{ needs.dockerBuildPush.outputs.image }}"
          VARS: ".nais/prod.yaml"
