name: "CI/CD Pipeline for sporingslogg-cleanup-job"
on:
  push:
    paths-ignore:
      - "**.md"
      - ".nais/alerts.yaml"
      - ".github/workflows/alerts.yaml"
      - "app/**"
      - "hent-utenlandsadresser/**"

jobs:
  build-and-deploy:
    uses: ./.github/build-and-deploy.yaml
    with:
      service_name: "sporingslogg-cleanup"
      docker_context: "./sporingslogg-cleanup"
      dockerfile: "./sporingslogg-cleanup/Dockerfile"
      resource_file: ".nais/sporingslogg-cleanup-job.yaml"